POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "Vídeo node",
  "description": "Esse é o vídeo teste",
  "duration": 90
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/cd651bf9-7031-4ce4-995d-6242a00bca98
Content-Type: application/json

{
  "title": "Vídeo 02",
  "description": "Esse é o vídeo teste",
  "duration": 90
}

###

DELETE http://localhost:3333/videos/1899fa7d-228c-4e86-8a5a-2bf1a8d73730